import { CategorySpec } from './types';

export const colaboradoresCategory: CategorySpec = {
  id: 'colaboradores',
  name: 'Colaboradores',
  description: 'Cadastro, edição, consulta e exclusão de colaboradores',
  icon: 'Users',
  endpoints: [
    {
      id: 'criar-colaborador',
      method: 'POST',
      path: '/api/v1/criar-colaborador',
      summary: 'Criar colaborador',
      auth: 'both',
      tags: ['colaboradores'],
      requestBody: {
        required: true,
        schema: {
          nome: { type: 'string', required: true, description: 'Nome completo (mín. 3 caracteres)' },
          email: { type: 'string', required: true, description: 'Email único' },
          cpf: { type: 'string', required: true, description: 'CPF (11-14 caracteres)' },
          senha: { type: 'string', required: true, description: 'Senha inicial (mín. 6)' },
          dataAdmissao: { type: 'date', required: true, description: 'Data de admissão' },
          rg: { type: 'string', description: 'RG' },
          telefone: { type: 'string', description: 'Telefone' },
          pis: { type: 'string', description: 'PIS/PASEP' },
          externalId: { type: 'string', description: 'ID externo para integração' },
          categoria: { type: 'string', description: 'Categoria', enum: ['empregado', 'usuario_interno'] },
          observacao: { type: 'string', description: 'Observações' },
          cargoId: { type: 'number', description: 'ID do cargo' },
          empresaId: { type: 'number', description: 'ID da empresa' },
          departamentoId: { type: 'number', description: 'ID do departamento' },
          jornadaId: { type: 'number', description: 'ID da jornada' },
          dataNascimento: { type: 'date', description: 'Data de nascimento' },
          dataDesligamento: { type: 'date', description: 'Data de desligamento' },
          endereco: { type: 'object', description: 'Endereço (objeto com cep, logradouro, numero, complemento, bairro, cidade, estado)' },
        },
        example: { nome: 'João Silva', email: 'joao@empresa.com', cpf: '123.456.789-00', senha: 'senha123', dataAdmissao: '2024-01-15', cargoId: 1, departamentoId: 1 },
      },
      responses: {
        success: { status: 201, description: 'Criado', example: { success: true, data: { id: 1, nome: 'João Silva', email: 'joao@empresa.com', mensagem: 'Colaborador criado com sucesso' } } },
        errors: [
          { status: 400, code: 'INVALID_CPF', message: 'CPF inválido' },
          { status: 400, code: 'DUPLICATE', message: 'Email ou CPF já cadastrado' },
        ],
      },
    },
    {
      id: 'listar-colaboradores',
      method: 'GET',
      path: '/api/v1/listar-colaboradores',
      summary: 'Listar colaboradores',
      auth: 'both',
      tags: ['colaboradores'],
      queryParams: {
        pagina: { type: 'number', description: 'Página (default: 1)' },
        limite: { type: 'number', description: 'Itens por página (default: 20)' },
        busca: { type: 'string', description: 'Busca por nome/email/CPF' },
        'filtro[departamentoId]': { type: 'number', description: 'Filtrar por departamento' },
        'filtro[status]': { type: 'string', description: 'Status', enum: ['ativo', 'inativo'] },
        orderBy: { type: 'string', description: 'Campo para ordenação' },
        orderDir: { type: 'string', description: 'Direção', enum: ['asc', 'desc'] },
      },
      responses: {
        success: { 
          status: 200, 
          description: 'Lista paginada', 
          example: { 
            success: true, 
            data: { 
              dados: [{ id: 1, nome: 'João', email: 'joao@empresa.com', cpf: '123...', cargo: { id: 1, nome: 'Analista' }, status: 'ativo', foto: null, dataAdmissao: '2024-01-15', empresa: { id: 1, nomeFantasia: 'Empresa' }, departamento: { id: 1, nome: 'TI' }, jornada: { id: 1, nome: 'Comercial' }, biometria: { cadastrada: true, cadastradaEm: '2024-01-16' } }], 
              total: 50, 
              pagina: 1, 
              limite: 20 
            } 
          } 
        },
        errors: [],
      },
    },
    {
      id: 'obter-colaborador',
      method: 'GET',
      path: '/api/v1/obter-colaborador/{id}',
      summary: 'Obter colaborador',
      description: 'Retorna dados completos do colaborador incluindo empresa, departamento, jornada e documentos.',
      auth: 'both',
      tags: ['colaboradores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do colaborador' } },
      responses: {
        success: { 
          status: 200, 
          description: 'Dados completos', 
          example: { 
            success: true, 
            data: { 
              id: 1, 
              nome: 'João Silva', 
              email: 'joao@empresa.com',
              cpf: '123.456.789-00',
              rg: '12.345.678-9',
              telefone: '(11) 99999-9999',
              pis: '123.45678.90-1',
              externalId: 'ext_123',
              tipo: 'colaborador',
              categoria: 'empregado',
              cargo: { id: 1, nome: 'Analista' },
              status: 'ativo',
              foto: '/storage/fotos/1.jpg',
              faceRegistrada: true,
              dataAdmissao: '2024-01-15',
              dataNascimento: '1990-05-20',
              dataDesligamento: null,
              endereco: { cep: '01234-567', logradouro: 'Rua X', numero: '100', bairro: 'Centro', cidade: 'São Paulo', estado: 'SP' },
              empresa: { id: 1, nomeFantasia: 'Empresa LTDA', cnpj: '12.345.678/0001-90', cidade: 'São Paulo', estado: 'SP' },
              departamento: { id: 1, nome: 'TI' },
              jornada: { id: 1, nome: 'Comercial 8h' },
              documentos: [{ id: 1, tipo: 'rg', nome: 'RG.pdf', url: '/storage/docs/1.pdf', dataUpload: '2024-01-15' }],
              criadoEm: '2024-01-15T10:00:00Z',
              atualizadoEm: '2024-01-16T14:30:00Z'
            } 
          } 
        },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Colaborador não encontrado' }],
      },
    },
    {
      id: 'atualizar-colaborador',
      method: 'PUT',
      path: '/api/v1/atualizar-colaborador/{id}',
      summary: 'Atualizar colaborador',
      auth: 'both',
      tags: ['colaboradores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do colaborador' } },
      requestBody: {
        required: true,
        schema: {
          nome: { type: 'string', description: 'Nome' },
          telefone: { type: 'string', description: 'Telefone' },
          cargoId: { type: 'number', description: 'ID do cargo' },
          departamentoId: { type: 'number', description: 'ID do departamento' },
          status: { type: 'string', description: 'Status do colaborador', enum: ['ativo', 'inativo'] },
          novaSenha: { type: 'string', description: 'Nova senha (apenas gestores/admins)' },
        },
        example: { nome: 'João da Silva Santos', cargoId: 2, novaSenha: 'NovaSenha@123' },
      },
      responses: {
        success: { status: 200, description: 'Atualizado', example: { success: true } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Colaborador não encontrado' }],
      },
    },
    {
      id: 'excluir-colaborador',
      method: 'DELETE',
      path: '/api/v1/excluir-colaborador/{id}',
      summary: 'Excluir colaborador',
      auth: 'both',
      tags: ['colaboradores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do colaborador' } },
      responses: {
        success: { status: 200, description: 'Excluído', example: { success: true } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Colaborador não encontrado' }],
      },
    },
    {
      id: 'obter-resumo-colaborador',
      method: 'GET',
      path: '/api/v1/obter-resumo-colaborador/{colaboradorId}',
      summary: 'Resumo do colaborador',
      description: 'Horas trabalhadas, banco de horas e marcações recentes.',
      auth: 'both',
      tags: ['colaboradores'],
      pathParams: { colaboradorId: { type: 'number', required: true, description: 'ID do colaborador' } },
      responses: {
        success: { status: 200, description: 'Resumo', example: { success: true, data: { horasTrabalhadas: '168:00', bancoHoras: '+12:30' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Colaborador não encontrado' }],
      },
    },
    {
      id: 'atualizar-foto-colaborador',
      method: 'PUT',
      path: '/api/v1/atualizar-foto-colaborador/{id}',
      summary: 'Atualizar foto',
      auth: 'both',
      tags: ['colaboradores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do colaborador' } },
      requestBody: {
        required: true,
        contentType: 'multipart/form-data',
        schema: { foto: { type: 'file', required: true, description: 'Imagem (JPEG, PNG)' } },
        example: {},
      },
      responses: {
        success: { status: 200, description: 'Atualizada', example: { success: true, data: { url: '/storage/foto.jpg' } } },
        errors: [{ status: 400, code: 'INVALID_FILE', message: 'Formato inválido' }],
      },
    },
    {
      id: 'obter-foto-colaborador',
      method: 'GET',
      path: '/api/v1/obter-foto-colaborador/{id}',
      summary: 'Obter foto',
      auth: 'both',
      tags: ['colaboradores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do colaborador' } },
      responses: {
        success: { status: 200, description: 'URL da foto', example: { success: true, data: { url: '/storage/foto.jpg' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Foto não encontrada' }],
      },
    },
  ],
};
