import { CategorySpec } from './types';

export const prestadoresCategory: CategorySpec = {
  id: 'prestadores',
  name: 'Prestadores de Serviços',
  description: 'Cadastro de prestadores, contratos e NFes',
  icon: 'Building',
  endpoints: [
    {
      id: 'listar-prestadores',
      method: 'GET',
      path: '/api/v1/listar-prestadores',
      summary: 'Lista prestadores (paginado)',
      auth: 'both',
      tags: ['prestadores'],
      queryParams: {
        busca: { type: 'string', description: 'Busca por razão social, nome fantasia ou CNPJ/CPF' },
        status: { type: 'string', description: 'Filtro: ativo | inativo | bloqueado', enum: ['ativo', 'inativo', 'bloqueado'] },
        pagina: { type: 'number', description: 'Página (default 1)' },
        limite: { type: 'number', description: 'Itens por página (default 50)' },
      },
      responses: {
        success: {
          status: 200,
          description: 'Lista de prestadores',
          example: {
            success: true,
            data: [{ id: 1, razaoSocial: 'Empresa X Ltda', nomeFantasia: 'Empresa X', cnpjCpf: '12.345.678/0001-90', tipo: 'PJ', email: 'contato@empresax.com', telefone: '(11) 99999-0000', endereco: 'Rua ABC, 123', areaAtuacao: 'TI', status: 'ativo', observacoes: '', createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-02-20T14:30:00Z' }],
            paginacao: { total: 45, pagina: 1, limite: 20, totalPaginas: 3 },
          },
        },
        errors: [{ status: 401, code: 'UNAUTHORIZED', message: 'Não autenticado' }],
      },
    },
    {
      id: 'obter-prestador',
      method: 'GET',
      path: '/api/v1/obter-prestador/{id}',
      summary: 'Obtém um prestador por ID',
      auth: 'both',
      tags: ['prestadores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do prestador' } },
      responses: {
        success: {
          status: 200,
          description: 'Dados do prestador',
          example: {
            success: true,
            data: { id: 1, razaoSocial: 'Empresa X Ltda', nomeFantasia: 'Empresa X', cnpjCpf: '12.345.678/0001-90', tipo: 'PJ', email: 'contato@empresax.com', telefone: '(11) 99999-0000', endereco: 'Rua ABC, 123 - São Paulo/SP', areaAtuacao: 'TI', status: 'ativo', observacoes: '', createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-02-20T14:30:00Z' },
          },
        },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Prestador não encontrado' }],
      },
    },
    {
      id: 'criar-prestador',
      method: 'POST',
      path: '/api/v1/criar-prestador',
      summary: 'Cadastra novo prestador',
      auth: 'both',
      tags: ['prestadores'],
      requestBody: {
        required: true,
        schema: {
          razaoSocial: { type: 'string', required: true, description: 'Razão social' },
          nomeFantasia: { type: 'string', description: 'Nome fantasia' },
          cnpjCpf: { type: 'string', required: true, description: 'CNPJ ou CPF' },
          email: { type: 'string', description: 'E-mail' },
          telefone: { type: 'string', description: 'Telefone' },
          endereco: { type: 'string', description: 'Endereço completo' },
          areaAtuacao: { type: 'string', description: 'Área de atuação (ex: TI)' },
          status: { type: 'string', description: 'ativo | inativo | bloqueado', enum: ['ativo', 'inativo', 'bloqueado'] },
          observacoes: { type: 'string', description: 'Observações' },
        },
        example: {
          razaoSocial: 'Empresa X Ltda',
          nomeFantasia: 'Empresa X',
          cnpjCpf: '12.345.678/0001-90',
          email: 'contato@empresax.com',
          telefone: '(11) 99999-0000',
          endereco: 'Rua ABC, 123 - São Paulo/SP',
          areaAtuacao: 'TI',
          status: 'ativo',
          observacoes: '',
        },
      },
      responses: {
        success: { status: 201, description: 'Prestador criado', example: { success: true, data: { id: 1, razaoSocial: 'Empresa X Ltda', nomeFantasia: 'Empresa X', cnpjCpf: '12.345.678/0001-90', tipo: 'PJ', email: 'contato@empresax.com', telefone: '(11) 99999-0000', endereco: 'Rua ABC, 123', areaAtuacao: 'TI', status: 'ativo', observacoes: '', createdAt: '2026-03-03T10:00:00Z', updatedAt: '2026-03-03T10:00:00Z' } } },
        errors: [{ status: 400, code: 'DUPLICATE', message: 'CNPJ/CPF já cadastrado' }, { status: 422, code: 'VALIDATION_ERROR', message: 'Erro de validação' }],
      },
    },
    {
      id: 'atualizar-prestador',
      method: 'PUT',
      path: '/api/v1/atualizar-prestador/{id}',
      summary: 'Atualiza um prestador',
      auth: 'both',
      tags: ['prestadores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do prestador' } },
      requestBody: {
        required: true,
        schema: {
          razaoSocial: { type: 'string', description: 'Razão social' },
          nomeFantasia: { type: 'string', description: 'Nome fantasia' },
          cnpjCpf: { type: 'string', description: 'CNPJ ou CPF' },
          email: { type: 'string', description: 'E-mail' },
          telefone: { type: 'string', description: 'Telefone' },
          endereco: { type: 'string', description: 'Endereço' },
          areaAtuacao: { type: 'string', description: 'Área de atuação' },
          status: { type: 'string', description: 'ativo | inativo | bloqueado', enum: ['ativo', 'inativo', 'bloqueado'] },
          observacoes: { type: 'string', description: 'Observações' },
        },
        example: { razaoSocial: 'Empresa X Ltda', nomeFantasia: 'Empresa X', status: 'ativo' },
      },
      responses: {
        success: { status: 200, description: 'Prestador atualizado', example: { success: true, data: { id: 1, razaoSocial: 'Empresa X Ltda', status: 'ativo', updatedAt: '2026-03-03T14:00:00Z' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Prestador não encontrado' }],
      },
    },
    {
      id: 'excluir-prestador',
      method: 'DELETE',
      path: '/api/v1/excluir-prestador/{id}',
      summary: 'Exclui um prestador',
      auth: 'both',
      tags: ['prestadores'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do prestador' } },
      responses: {
        success: { status: 204, description: 'Prestador excluído', example: {} },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Prestador não encontrado' }],
      },
    },
    {
      id: 'listar-contratos-prestador',
      method: 'GET',
      path: '/api/v1/listar-contratos-prestador',
      summary: 'Lista contratos de prestadores (paginado)',
      auth: 'both',
      tags: ['prestadores', 'contratos'],
      queryParams: {
        prestador_id: { type: 'number', description: 'Filtra por ID do prestador' },
        status: { type: 'string', description: 'vigente | vencido | renovado | cancelado', enum: ['vigente', 'vencido', 'renovado', 'cancelado'] },
        busca: { type: 'string', description: 'Busca por número ou descrição' },
        pagina: { type: 'number', description: 'Página' },
        limite: { type: 'number', description: 'Itens por página' },
      },
      responses: {
        success: {
          status: 200,
          description: 'Lista de contratos',
          example: {
            success: true,
            data: [{ id: 1, prestadorId: 1, prestadorNome: 'Empresa X', numero: 'CT-2026-001', descricao: 'Manutenção de servidores', dataInicio: '2026-01-01', dataFim: '2026-12-31', valor: 5000, formaPagamento: 'mensal', status: 'vigente', alertaRenovacaoDias: 30, observacoes: '', createdAt: '2026-01-01T10:00:00Z', updatedAt: '2026-01-01T10:00:00Z' }],
            paginacao: { total: 10, pagina: 1, limite: 20, totalPaginas: 1 },
          },
        },
        errors: [],
      },
    },
    {
      id: 'criar-contrato-prestador',
      method: 'POST',
      path: '/api/v1/criar-contrato-prestador',
      summary: 'Cria contrato vinculado a um prestador',
      auth: 'both',
      tags: ['prestadores', 'contratos'],
      requestBody: {
        required: true,
        schema: {
          prestadorId: { type: 'number', required: true, description: 'ID do prestador' },
          numero: { type: 'string', required: true, description: 'Número do contrato' },
          descricao: { type: 'string', description: 'Descrição' },
          dataInicio: { type: 'string', required: true, description: 'Data início (YYYY-MM-DD)' },
          dataFim: { type: 'string', description: 'Data fim (YYYY-MM-DD)' },
          valor: { type: 'number', required: true, description: 'Valor' },
          formaPagamento: { type: 'string', required: true, description: 'mensal | quinzenal | por_demanda | unico', enum: ['mensal', 'quinzenal', 'por_demanda', 'unico'] },
          status: { type: 'string', description: 'vigente | vencido | renovado | cancelado', enum: ['vigente', 'vencido', 'renovado', 'cancelado'] },
          alertaRenovacaoDias: { type: 'number', description: 'Dias para alertar renovação (default 30)' },
          observacoes: { type: 'string', description: 'Observações' },
        },
        example: {
          prestadorId: 1,
          numero: 'CT-2026-001',
          descricao: 'Manutenção de servidores',
          dataInicio: '2026-01-01',
          dataFim: '2026-12-31',
          valor: 5000,
          formaPagamento: 'mensal',
          status: 'vigente',
          alertaRenovacaoDias: 30,
          observacoes: '',
        },
      },
      responses: {
        success: { status: 201, description: 'Contrato criado', example: { success: true, data: { id: 1, prestadorId: 1, prestadorNome: 'Empresa X', numero: 'CT-2026-001', descricao: 'Manutenção de servidores', dataInicio: '2026-01-01', dataFim: '2026-12-31', valor: 5000, formaPagamento: 'mensal', status: 'vigente', alertaRenovacaoDias: 30, observacoes: '', createdAt: '2026-03-03T10:00:00Z', updatedAt: '2026-03-03T10:00:00Z' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Prestador não encontrado' }],
      },
    },
    {
      id: 'atualizar-contrato-prestador',
      method: 'PUT',
      path: '/api/v1/atualizar-contrato-prestador/{id}',
      summary: 'Atualiza um contrato de prestador',
      auth: 'both',
      tags: ['prestadores', 'contratos'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do contrato' } },
      requestBody: {
        required: true,
        schema: {
          prestadorId: { type: 'number', description: 'ID do prestador' },
          numero: { type: 'string', description: 'Número do contrato' },
          descricao: { type: 'string', description: 'Descrição' },
          dataInicio: { type: 'string', description: 'Data início' },
          dataFim: { type: 'string', description: 'Data fim' },
          valor: { type: 'number', description: 'Valor' },
          formaPagamento: { type: 'string', description: 'Forma de pagamento', enum: ['mensal', 'quinzenal', 'por_demanda', 'unico'] },
          status: { type: 'string', description: 'Status', enum: ['vigente', 'vencido', 'renovado', 'cancelado'] },
          alertaRenovacaoDias: { type: 'number', description: 'Dias alerta renovação' },
          observacoes: { type: 'string', description: 'Observações' },
        },
        example: { status: 'renovado', valor: 6000 },
      },
      responses: {
        success: { status: 200, description: 'Contrato atualizado', example: { success: true, data: { id: 1, numero: 'CT-2026-001', status: 'renovado', updatedAt: '2026-03-03T14:00:00Z' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Contrato não encontrado' }],
      },
    },
    {
      id: 'excluir-contrato-prestador',
      method: 'DELETE',
      path: '/api/v1/excluir-contrato-prestador/{id}',
      summary: 'Exclui um contrato de prestador',
      auth: 'both',
      tags: ['prestadores', 'contratos'],
      pathParams: { id: { type: 'number', required: true, description: 'ID do contrato' } },
      responses: {
        success: { status: 204, description: 'Contrato excluído', example: {} },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Contrato não encontrado' }],
      },
    },
    {
      id: 'listar-nfes-prestador',
      method: 'GET',
      path: '/api/v1/listar-nfes-prestador',
      summary: 'Lista NFes de prestadores (paginado)',
      auth: 'both',
      tags: ['prestadores', 'nfes'],
      queryParams: {
        prestador_id: { type: 'number', description: 'Filtra por prestador' },
        contrato_id: { type: 'number', description: 'Filtra por contrato' },
        status: { type: 'string', description: 'pendente | aprovada | rejeitada | paga', enum: ['pendente', 'aprovada', 'rejeitada', 'paga'] },
        busca: { type: 'string', description: 'Busca por número ou chave de acesso' },
        pagina: { type: 'number', description: 'Página' },
        limite: { type: 'number', description: 'Itens por página' },
      },
      responses: {
        success: {
          status: 200,
          description: 'Lista de NFes',
          example: {
            success: true,
            data: [{ id: 1, prestadorId: 1, prestadorNome: 'Empresa X', contratoId: 1, contratoNumero: 'CT-2026-001', numero: '000123', serie: '1', chaveAcesso: '35260612345678000190550010001230001234567890', dataEmissao: '2026-02-01', valor: 5000, status: 'pendente', arquivoUrl: '', observacoes: '', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' }],
            paginacao: { total: 5, pagina: 1, limite: 20, totalPaginas: 1 },
          },
        },
        errors: [],
      },
    },
    {
      id: 'criar-nfe-prestador',
      method: 'POST',
      path: '/api/v1/criar-nfe-prestador',
      summary: 'Cadastra NFe de prestador',
      auth: 'both',
      tags: ['prestadores', 'nfes'],
      requestBody: {
        required: true,
        schema: {
          prestadorId: { type: 'number', required: true, description: 'ID do prestador' },
          contratoId: { type: 'number', description: 'ID do contrato (opcional)' },
          numero: { type: 'string', required: true, description: 'Número da NFe' },
          serie: { type: 'string', description: 'Série' },
          chaveAcesso: { type: 'string', description: 'Chave de acesso (44 dígitos)' },
          dataEmissao: { type: 'string', required: true, description: 'Data emissão (YYYY-MM-DD)' },
          valor: { type: 'number', required: true, description: 'Valor' },
          status: { type: 'string', description: 'pendente | aprovada | rejeitada | paga', enum: ['pendente', 'aprovada', 'rejeitada', 'paga'] },
          arquivoUrl: { type: 'string', description: 'URL do arquivo PDF/XML' },
          observacoes: { type: 'string', description: 'Observações' },
        },
        example: {
          prestadorId: 1,
          contratoId: 1,
          numero: '000123',
          serie: '1',
          chaveAcesso: '35260612345678000190550010001230001234567890',
          dataEmissao: '2026-02-01',
          valor: 5000,
          status: 'pendente',
          arquivoUrl: '',
          observacoes: '',
        },
      },
      responses: {
        success: { status: 201, description: 'NFe criada', example: { success: true, data: { id: 1, prestadorId: 1, prestadorNome: 'Empresa X', contratoId: 1, contratoNumero: 'CT-2026-001', numero: '000123', serie: '1', dataEmissao: '2026-02-01', valor: 5000, status: 'pendente', createdAt: '2026-03-03T10:00:00Z', updatedAt: '2026-03-03T10:00:00Z' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'Prestador ou contrato não encontrado' }],
      },
    },
    {
      id: 'atualizar-nfe-prestador',
      method: 'PUT',
      path: '/api/v1/atualizar-nfe-prestador/{id}',
      summary: 'Atualiza uma NFe de prestador',
      auth: 'both',
      tags: ['prestadores', 'nfes'],
      pathParams: { id: { type: 'number', required: true, description: 'ID da NFe' } },
      requestBody: {
        required: true,
        schema: {
          prestadorId: { type: 'number', description: 'ID do prestador' },
          contratoId: { type: 'number', description: 'ID do contrato' },
          numero: { type: 'string', description: 'Número da NFe' },
          serie: { type: 'string', description: 'Série' },
          chaveAcesso: { type: 'string', description: 'Chave de acesso' },
          dataEmissao: { type: 'string', description: 'Data emissão' },
          valor: { type: 'number', description: 'Valor' },
          status: { type: 'string', description: 'Status', enum: ['pendente', 'aprovada', 'rejeitada', 'paga'] },
          arquivoUrl: { type: 'string', description: 'URL do arquivo' },
          observacoes: { type: 'string', description: 'Observações' },
        },
        example: { status: 'aprovada', arquivoUrl: 'https://storage.exemplo.com/nfes/nfe-000123.pdf' },
      },
      responses: {
        success: { status: 200, description: 'NFe atualizada', example: { success: true, data: { id: 1, numero: '000123', status: 'aprovada', updatedAt: '2026-03-03T14:00:00Z' } } },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'NFe não encontrada' }],
      },
    },
    {
      id: 'excluir-nfe-prestador',
      method: 'DELETE',
      path: '/api/v1/excluir-nfe-prestador/{id}',
      summary: 'Exclui uma NFe de prestador',
      auth: 'both',
      tags: ['prestadores', 'nfes'],
      pathParams: { id: { type: 'number', required: true, description: 'ID da NFe' } },
      responses: {
        success: { status: 204, description: 'NFe excluída', example: {} },
        errors: [{ status: 404, code: 'NOT_FOUND', message: 'NFe não encontrada' }],
      },
    },
  ],
};
